# Data Cleaning

In [ ]:
#import necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# importing the dataset into a dataframe
df = pd.read_csv('/home/raph/Documents/Data Science/Solavise women in data/csv files/archive (2)/Independent_Medical_Reviews.csv')

## Studying the data set

This section will be dedicated to studying and understanding the dataset and cleaning it up, filling missing values, deleting duplicates

In [6]:
df.head()

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
0,MN16-22639,2016,Infectious,Hepatitis,Pharmacy/Prescription Drugs,Anti-virals,Overturned Decision of Health Plan,Medical Necessity,41-50,Male,Nature of Statutory Criteria/Case Summary: An ...
1,MN16-22638,2016,Mental,Eating Disorder,Mental Health Treatment,Residential Treatment Center - Admission,Upheld Decision of Health Plan,Medical Necessity,21-30,Female,Nature of Statutory Criteria/Case Summary: An...
2,MN16-22637,2016,Autism Spectrum,Autism-PDD-NOS,Autism Related Treatment,Speech Therapy,Upheld Decision of Health Plan,Medical Necessity,0-10,Female,Nature of Statutory Criteria/Case Summary: Th...
3,EI16-22636,2016,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,65+,Female,Nature of Statutory Criteria/Case Summary: An ...
4,EI06-5319,2006,Cardiac/Circulatory,NaN,Cardio Vascular,NaN,Upheld Decision of Health Plan,Experimental/Investigational,51-64,Male,Physician 1: The patient is a 62-year-old male...

In [7]:
df.tail()

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
19240,MN01-7,2001,Trauma/Injuries,Gunshot Wound,Neurosugery,Cranioplasty,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,The parents of a 17-year-old male requested a ...
19241,MN01-6,2001,Infectious,Onychomycosis/ Nail Fungus,Pharmacy/Prescription Drugs,Anti-Fungal,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 46-year-old male requested Penlac lacquer fo...
19242,MN01-5,2001,Orthopedic/ Musculoskeletal,Other,Orthopedic,Arthroscopy,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 46-year-old female requested an orthoscopic ...
19243,MN01-4,2001,Orthopedic/ Musculoskeletal,Back Pain,Reconstructive/Plastic Surgery,Breast Reduction,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,A 24-year-old female requested a bilateral bre...
19244,EI01-3,2001,Cancer,Lung Cancer,Cancer Treatment,Clinical Trial (Phase 1),Upheld Decision of Health Plan,Experimental/Investigational,NaN,NaN,A male requested participation in a Phase I st...

In [4]:
df.shape

(19245, 11)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19245 entries, 0 to 19244
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Reference ID            19245 non-null  object
 1   Report Year             19245 non-null  int64
 2   Diagnosis Category      19186 non-null  object
 3   Diagnosis Sub Category  17341 non-null  object
 4   Treatment Category      18795 non-null  object
 5   Treatment Sub Category  17977 non-null  object
 6   Determination           19245 non-null  object
 7   Type                    19245 non-null  object
 8   Age Range               18035 non-null  object
 9   Patient Gender          18035 non-null  object
 10  Findings                19225 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.6+ MB

In [9]:
df.describe()

        Report Year
count  19245.000000
mean    2009.662977
std        4.272045
min     2001.000000
25%     2007.000000
50%     2010.000000
75%     2014.000000
max     2016.000000

In [10]:
df.isnull().sum()

Reference ID                 0
Report Year                  0
Diagnosis Category          59
Diagnosis Sub Category    1904
Treatment Category         450
Treatment Sub Category    1268
Determination                0
Type                         0
Age Range                 1210
Patient Gender            1210
Findings                    20
dtype: int64

### Filling missing data in the gender and age range columns

In [21]:
age_missing = df[df['Age Range'].isnull()]
age_missing

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
360,EI01-434,2001,Orthopedic/ Musculoskeletal,Back Pain,Electrical/ Thermal/ Radiofreq. Interventions,IDET,Upheld Decision of Health Plan,Experimental/Investigational,NaN,NaN,A 37-year-old female requested intradiscal ele...
366,EI01-408,2001,Orthopedic/ Musculoskeletal,Joint Problem,Orthopedic,Other,Upheld Decision of Health Plan,Experimental/Investigational,NaN,NaN,A fifty-one year old male with bilateral hip p...
822,MN01-79,2001,Digestive System/ Gastrointestinal,Other,Alternative Treatment,Biofeedback,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 39-year-old female requested biofeedback the...
832,MN01-74,2001,Digestive System/ Gastrointestinal,GERDs/ Reflux Disorders,Pharmacy/Prescription Drugs,Antacids,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,A 62-year-old female requested a prescription ...
1100,MN01-73,2001,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Colonoscopy,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,A 58-year-old female requested a colonoscopy f...
...,...,...,...,...,...,...,...,...,...,...,...
19240,MN01-7,2001,Trauma/Injuries,Gunshot Wound,Neurosugery,Cranioplasty,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,The parents of a 17-year-old male requested a ...
19241,MN01-6,2001,Infectious,Onychomycosis/ Nail Fungus,Pharmacy/Prescription Drugs,Anti-Fungal,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 46-year-old male requested Penlac lacquer fo...
19242,MN01-5,2001,Orthopedic/ Musculoskeletal,Other,Orthopedic,Arthroscopy,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 46-year-old female requested an orthoscopic ...
19243,MN01-4,2001,Orthopedic/ Musculoskeletal,Back Pain,Reconstructive/Plastic Surgery,Breast Reduction,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,A 24-year-old female requested a bilateral bre...
19244,EI01-3,2001,Cancer,Lung Cancer,Cancer Treatment,Clinical Trial (Phase 1),Upheld Decision of Health Plan,Experimental/Investigational,NaN,NaN,A male requested participation in a Phase I st...

In [45]:
# extracting the age and sex from the findings column
import re

def age_range(age):
    if age < 11:
        return '0-10'
    elif age < 21:
        return '11-20'
    elif age < 31:
        return '21-30'
    elif age < 41:
        return '31-40'
    elif age < 51:
        return '41-50'
    elif age < 65:
        return '51-64'
    else:
        return '65+'

def pat_gender(text):
    text = text.lower()
    if text == 'male' or text == 'man':
        return 'Male'
    elif text =='female' or text == 'woman':
        return 'Female'
    else:
        return None

def fill_missing_age_sex(text):
    match = re.search(r'(\d+)[-\s]*year[-\s]*old\s+(male|female|man|woman)', text, re.IGNORECASE)
    if match:
        age = age_range(int(match.group(1))) if match.group(1) else None
        gender = pat_gender(match.group(2)) if match.group(2) else None
        return age, gender


df[['Age Range', 'Patient Gender']] = df.apply(lambda row: fill_missing_age_sex(row['Findings']) if pd.isnull(row['Age Range']) or pd.isnull(row['Patient Gender']) else (row['Age Range'], row['Patient Gender']), axis=1, result_type='expand')

In [50]:
def fill_missing_gender(text):
    match = re.search(r'(female|male)', text, re.IGNORECASE)
    if match:
        gender = pat_gender(match.group(1)) if match.group(1) else None
        return gender
    
df['Patient Gender'] = df.apply(lambda row: fill_missing_gender(row['Findings']) if pd.isnull(row['Patient Gender']) else row['Patient Gender'], axis=1)

In [51]:
def fill_missing_age(text):
    match = re.search(r'(\d+)[-\s]*year[-\s]*old', text, re.IGNORECASE)
    if match:
        age = age_range(int(match.group(1))) if match.group(1) else None
        return age  

df['Age Range'] = df.apply(lambda row: fill_missing_age(row['Findings']) if pd.isnull(row['Age Range']) else row['Age Range'], axis=1)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19245 entries, 0 to 19244
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Reference ID            19245 non-null  object
 1   Report Year             19245 non-null  int64
 2   Diagnosis Category      19186 non-null  object
 3   Diagnosis Sub Category  17341 non-null  object
 4   Treatment Category      18795 non-null  object
 5   Treatment Sub Category  17977 non-null  object
 6   Determination           19245 non-null  object
 7   Type                    19245 non-null  object
 8   Age Range               19178 non-null  object
 9   Patient Gender          19242 non-null  object
 10  Findings                19225 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.6+ MB

In [48]:
gender_missing = df[df['Patient Gender'].isnull()]
gender_missing

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
366,EI01-408,2001,Orthopedic/ Musculoskeletal,Joint Problem,Orthopedic,Other,Upheld Decision of Health Plan,Experimental/Investigational,None,None,A fifty-one year old male with bilateral hip p...
5999,MN01-62,2001,"Ears, Nose, Throat",Sinusitis - Sinus Infections,Pharmacy/Prescription Drugs,Anti-Fungal,Upheld Decision of Health Plan,Medical Necessity,None,None,A female enrollee requested the prescription d...
18046,EI02-1392,2002,Mental,Autism,Mental Health Treatment,Behavioral Therapy,Upheld Decision of Health Plan,Experimental/Investigational,None,None,The parents of a male enrollee requested autho...
18082,MN02-1344,2002,Mental,Other,Mental Health Treatment,Residential Treatment Center - Admission,Overturned Decision of Health Plan,Medical Necessity,None,None,The parents of a male enrollee requested autho...
18122,MN02-1295,2002,Infectious,Onychomycosis/ Nail Fungus,Pharmacy/Prescription Drugs,Anti-Fungal,Overturned Decision of Health Plan,Medical Necessity,None,None,A female enrollee requested authorization and ...
...,...,...,...,...,...,...,...,...,...,...,...
18983,MN01-280,2001,Vision,Eyelid Droop,Reconstructive/Plastic Surgery,Blepharoplasty,Upheld Decision of Health Plan,Medical Necessity,None,None,A 54-year-old enrollee requested bilateral ble...
19040,MN01-223,2001,Respiratory System,Other,Pharmacy/Prescription Drugs,Formulary versus Non-Formulary,Upheld Decision of Health Plan,Medical Necessity,None,None,The parents of an 18-month old female requeste...
19044,MN01-219,2001,Genetic,Other,Home Health Care,Skilled Nursing Visits,Overturned Decision of Health Plan,Medical Necessity,None,None,The mother of a 6-month-old male requested hom...
19177,MN01-82,2001,Morbid Obesity,Hypertension,Pharmacy/Prescription Drugs,Weight Control,Overturned Decision of Health Plan,Medical Necessity,None,None,A male requested the prescription medication X...
19244,EI01-3,2001,Cancer,Lung Cancer,Cancer Treatment,Clinical Trial (Phase 1),Upheld Decision of Health Plan,Experimental/Investigational,None,None,A male requested participation in a Phase I st...

In [53]:
age_missing = df[df['Age Range'].isnull()]
age_missing

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
366,EI01-408,2001,Orthopedic/ Musculoskeletal,Joint Problem,Orthopedic,Other,Upheld Decision of Health Plan,Experimental/Investigational,None,Male,A fifty-one year old male with bilateral hip p...
5999,MN01-62,2001,"Ears, Nose, Throat",Sinusitis - Sinus Infections,Pharmacy/Prescription Drugs,Anti-Fungal,Upheld Decision of Health Plan,Medical Necessity,None,Female,A female enrollee requested the prescription d...
18046,EI02-1392,2002,Mental,Autism,Mental Health Treatment,Behavioral Therapy,Upheld Decision of Health Plan,Experimental/Investigational,None,Male,The parents of a male enrollee requested autho...
18082,MN02-1344,2002,Mental,Other,Mental Health Treatment,Residential Treatment Center - Admission,Overturned Decision of Health Plan,Medical Necessity,None,Male,The parents of a male enrollee requested autho...
18122,MN02-1295,2002,Infectious,Onychomycosis/ Nail Fungus,Pharmacy/Prescription Drugs,Anti-Fungal,Overturned Decision of Health Plan,Medical Necessity,None,Female,A female enrollee requested authorization and ...
...,...,...,...,...,...,...,...,...,...,...,...
18961,MN01-301,2001,Genitourinary/ Kidney,Other,Pharmacy/Prescription Drugs,Other,Upheld Decision of Health Plan,Medical Necessity,None,Male,A male (age unknown) requested the prescriptio...
19040,MN01-223,2001,Respiratory System,Other,Pharmacy/Prescription Drugs,Formulary versus Non-Formulary,Upheld Decision of Health Plan,Medical Necessity,None,Female,The parents of an 18-month old female requeste...
19044,MN01-219,2001,Genetic,Other,Home Health Care,Skilled Nursing Visits,Overturned Decision of Health Plan,Medical Necessity,None,Male,The mother of a 6-month-old male requested hom...
19177,MN01-82,2001,Morbid Obesity,Hypertension,Pharmacy/Prescription Drugs,Weight Control,Overturned Decision of Health Plan,Medical Necessity,None,Male,A male requested the prescription medication X...
19244,EI01-3,2001,Cancer,Lung Cancer,Cancer Treatment,Clinical Trial (Phase 1),Upheld Decision of Health Plan,Experimental/Investigational,None,Male,A male requested participation in a Phase I st...

### Working on understanding the Diagnosis Category and sub category to fill the missing values

In [11]:
# selecting the rows where Diagnosis Category is 'Prevention/Good Health'
prevention_df = df[df['Diagnosis Category'] == 'Prevention/Good Health']
prevention_df

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
3,EI16-22636,2016,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,65+,Female,Nature of Statutory Criteria/Case Summary: An ...
5,EI16-22635,2016,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Lab Work,Upheld Decision of Health Plan,Experimental/Investigational,21-30,Male,Nature of Statutory Criteria/Case Summary: An...
11,EI16-22630,2016,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,51-64,Female,Nature of Statutory Criteria/Case Summary: An...
20,EI16-22623,2016,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,51-64,Female,Nature of Statutory Criteria/Case Summary: An ...
43,EI16-22604,2016,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Mammography,Upheld Decision of Health Plan,Experimental/Investigational,51-64,Female,Nature of Statutory Criteria/Case Summary: A...
...,...,...,...,...,...,...,...,...,...,...,...
19027,MN01-236,2001,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Colonoscopy,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 64-year old female requested a colonoscopy d...
19059,MN01-204,2001,Prevention/Good Health,NaN,OB/GYN Procedures,Hysterectomy,Overturned Decision of Health Plan,Medical Necessity,NaN,NaN,A 52-year-old female requested a prophylactic ...
19108,MN01-156,2001,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",PET Scan,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 65-year-old male enrollee requested a whole ...
19124,MN01-138,2001,Prevention/Good Health,NaN,Diagnostic/Physician Evaluation,Specialty Consultation Referral,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 53-year old male enrollee requested a referr...
19130,MN01-132,2001,Prevention/Good Health,NaN,"Diagnostic Imaging, Screening and Testing",Colonoscopy,Upheld Decision of Health Plan,Medical Necessity,NaN,NaN,A 60-year-old female requested a colonoscopy a...

In [12]:
prevention_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 300 entries, 3 to 19130
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Reference ID            300 non-null    object
 1   Report Year             300 non-null    int64
 2   Diagnosis Category      300 non-null    object
 3   Diagnosis Sub Category  6 non-null      object
 4   Treatment Category      300 non-null    object
 5   Treatment Sub Category  282 non-null    object
 6   Determination           300 non-null    object
 7   Type                    300 non-null    object
 8   Age Range               282 non-null    object
 9   Patient Gender          282 non-null    object
 10  Findings                300 non-null    object
dtypes: int64(1), object(10)
memory usage: 28.1+ KB

In [13]:
prevention_df['Diagnosis Sub Category'].value_counts()

Diagnosis Sub Category
Other                     2
Fibroids                  1
Thyroid Problems          1
Breast Cancer             1
Female Breast Disorder    1
Name: count, dtype: int64

In [16]:
prevention_df[prevention_df['Diagnosis Sub Category'].notnull()]

,Reference ID,Report Year,Diagnosis Category,Diagnosis Sub Category,Treatment Category,Treatment Sub Category,Determination,Type,Age Range,Patient Gender,Findings
182,EI16-22489,2016,Prevention/Good Health,Fibroids,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,65+,Female,Nature of Statutory Criteria/Case Summary: An ...
236,EI16-22443,2016,Prevention/Good Health,Other,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,51-64,Female,Nature of Statutory Criteria/Case Summary: A...
592,MN15-20102,2015,Prevention/Good Health,Thyroid Problems,"Diagnostic Imaging, Screening and Testing",Other,Upheld Decision of Health Plan,Medical Necessity,21-30,Female,A female enrollee requested BRAC Analysis Larg...
682,EI16-22061,2016,Prevention/Good Health,Other,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,51-64,Female,Nature of Statutory Criteria/Case Summary: A...
946,EI16-21838,2016,Prevention/Good Health,Breast Cancer,"Diagnostic Imaging, Screening and Testing",Mammography,Overturned Decision of Health Plan,Experimental/Investigational,65+,Female,Nature of Statutory Criteria/Case Summary: An...
6991,EI12-13908,2012,Prevention/Good Health,Female Breast Disorder,"Diagnostic Imaging, Screening and Testing",MRI,Upheld Decision of Health Plan,Experimental/Investigational,51-64,Female,A 52-year-old female has requested bilateral M...